name: ci
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:
    branches: [ master ]
permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y libxml2 libxml2-dev libxslt1-dev
        uv sync --all-extras --dev
    
    - name: Test with pytest
      run: uv run pytest

    - name: Minimize uv cache
      run: uv cache prune --ci
